/**
 * A map between file extensions and their corresponding MIME types.
 * @type {Object.<string, string>}
 * @module mimeTypeMap
 */
module.exports = {
  'md': 'text/markdown',
  'yml': 'application/x-yaml',
  'yaml': 'application/x-yaml',
  'sql': 'application/sql',
  'tex': 'application/x-latex',
  'r': 'text/x-r-source',
  'go': 'text/x-go',
  'groovy': 'text/x-groovy',
  'kt': 'text/x-kotlin',
  'kts': 'text/x-kotlin',
  'rs': 'text/x-rust',
  'ts': 'text/x-typescript',
  'txt': 'text/plain',
  'html': 'text/html',
  'htm': 'text/html',
  'css': 'text/css',
  'js': 'application/javascript',
  'json': 'application/json',
  'xml': 'application/xml',
  'csv': 'text/csv',
  'pdf': 'application/pdf',
  'jpg': 'image/jpeg',
  'jpeg': 'image/jpeg',
  'png': 'image/png',
  'gif': 'image/gif',
  'bmp': 'image/bmp',
  'ico': 'image/x-icon',
  'svg': 'image/svg+xml',
  'webp': 'image/webp',
  'tif': 'image/tiff',
  'tiff': 'image/tiff',
  'mp3': 'audio/mpeg',
  'wav': 'audio/wav',
  'ogg': 'audio/ogg',
  'mp4': 'video/mp4',
  'webm': 'video/webm',
  'avi': 'video/x-msvideo',
  'mov': 'video/quicktime',
  'zip': 'application/zip',
  'gz': 'application/gzip',
  'tar': 'application/x-tar',
  '7z': 'application/x-7z-compressed',
  'php': 'application/x-httpd-php',
  'py': 'text/x-python',
  'rb': 'text/x-ruby',
  'swift': 'text/x-swift',
  'c': 'text/x-csrc',
  'cpp': 'text/x-c++src',
  'java': 'text/x-java-source',
}
